### ISSUE TITLE
`1.1.1.0/24` and many other CIDRs belong to wrong country iso_code

### ISSUE THREAD

**Issue by Loyalsoldier** [oschwald/maxminddb-golang#147]
I find out that `1.1.1.0/24` and many other CIDRs belong to wrong country iso_code.

In file `GeoLite2-Country-CSV_20240730/GeoLite2-Country-Blocks-IPv4.csv`, `1.1.1.0/24` shows:

```csv
network,geoname_id,registered_country_geoname_id,represented_country_geoname_id,is_anonymous_proxy,is_satellite_provider,is_anycast
1.1.1.0/24,,2077456,,0,0,
```

it has no `geoname_id (country iso_code)` but `registered_country_geoname_id (registered_country iso_code)` showed as `Australia`.

But when reading the file `GeoLite2-Country_20240730/GeoLite2-Country.mmdb` by Golang:

```go
package main

import (
	"fmt"
	"log"

	"github.com/oschwald/maxminddb-golang"
)

func main() {
	db, err := maxminddb.Open("./GeoLite2-Country_20240730/GeoLite2-Country.mmdb")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	record := struct {
		Country struct {
			IsoCode string `maxminddb:"iso_code"`
		} `maxminddb:"country"`
		RegisteredCountry struct {
			IsoCode string `maxminddb:"iso_code"`
		} `maxminddb:"registered_country"`
		RepresentedCountry struct {
			IsoCode string `maxminddb:"iso_code"`
		} `maxminddb:"represented_country"`
	}{}

	networks := db.Networks(maxminddb.SkipAliasedNetworks)
	for networks.Next() {
		subnet, err := networks.Network(&record)
		if err != nil {
			log.Panic(err)
		}

		fmt.Printf("%s - %s - %s - %s\n", subnet.String(), record.Country.IsoCode, record.RegisteredCountry.IsoCode, record.RepresentedCountry.IsoCode)
	}
	if networks.Err() != nil {
		log.Panic(networks.Err())
	}
}
```

The output shows something like this:

```
1.1.1.0/24 - CN - AU - 
```

it has `country iso_code` showed as `China` and `registered_country iso_code` showed as `Australia`.

**Comment by oschwald** [comment]
The issue is that you are reusing `record` between iterations. The reader only sets values that are in the actual record in the database and will not zero out the other record. If you move `record` to inside the loop, I suspect you will get the behavior you are expecting.

I updated the examples so that people are less likely to make this mistake. With the Domain database in the example, it doesn't matter, as there is only a single value in the database, but it does matter with more complex databases such as the Country database.

**Comment by Loyalsoldier** [comment]
Oh, thanks.
